baseURL: https://amatiasq.com
languageCode: en-uk
title: A. Matías Quezada

# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds:
  - taxonomy
  - taxonomyTerm
