server {
    listen 80;

    location / {
        proxy_pass https://amatiasq.github.io;
        proxy_redirect https://amatiasq.github.io/amatiasq.com/ https://amatiasq.com/;
        rewrite /(.*) /amatiasq.com/$1 break;
    }

    # WORK
    # location /cv {
    #     return 301 /cv-en;
    # }
    location /cv-en {
        return 301 https://docs.google.com/document/d/1-OYtRQZ8rYQ8ipNY2rnNX4Nk_hlUn1LHRpIUW61v2Qw;
    }

    location /cv-es {
        return 301 https://docs.google.com/document/d/18jratWj56Wnc8yqsDn7KCKG7QwOex997iPOWZB92SNc;
    }

    location /mind-optimization {
        return 301 https://docs.google.com/presentation/d/1RwhPceNap0HqJ_gZyviY1W21_ex9abARuTHJjtTqh-E/edit;
    }

    # BOOKS

    location /book/limites {
        default_type "text/html";
        alias /www/libros/el-arte-de-poner-limites.html;
    }

    # /meme/$a should show files in /www/memes/$a with the extension name found in the file system
    # /meme/sir should show /www/memes/sir.jpg
    # /meme/no should show /www/memes/no.jpeg
    # /meme/reydios should show /www/memes/reydios.png
    # /meme/pacha should show /www/memes/pacha.webp
    location ~ ^/meme/(?<name>[a-z]+)$ {
        root /www/memes;
        try_files /$name.jpg /$name.jpeg /$name.png /$name.webp /$name.gif =404;
    }

    # UTIL

    location = /template {
	default_type "text/html";
	alias /www/template.html;
    }

    location = /people {
	default_type "text/html";
	alias /www/people.html;
    }

    location = /matrix {
        default_type "text/html";
        alias /www/matrix.html;
    }

    location = /js {
        default_type "image/gif";
        alias /www/javascript.gif;
    }

    location = /deno.ts {
	default_type "application/typescript";
	alias /www/deno.ts;
    }

    location = /blank {
        default_type "text/html";
        alias /www/blank.html;
    }

    location = /speedback {
        default_type "text/html";
        alias /www/speedback.html;
    }

    location = /plot {
        default_type "image/gif";
        alias /www/quaternaryplot.gif;
    }

    location = /es/dnd-sheet {
        default_type "application/pdf";
        alias /www/dnd-sheet.pdf;
	add_header Access-Control-Allow-Origin "*";
	add_header Access-Control-Allow-Methods "GET";
    }

    location = /s {
        default_type "text/html";
        alias /www/secret.html;
    }

    location = /secret {
        # default_type "text/html";
        # alias /www/secret.html;
        proxy_pass https://gist.githubusercontent.com/amatiasq/772058eb19c9e188c1e3d1e526d24762/raw;
        proxy_hide_header Content-Type;
        add_header Content-Type text/html;
        # this header prevents inline-scripts and inline-styles for some reason
        proxy_hide_header Content-Security-Policy;
        add_header Content-Security-Policy "default-src https: 'unsafe-inline'; object-src 'none'";
    }

    location /install {
        return 301 https://raw.githubusercontent.com/amatiasq/bin/master/install/install.sh;
    }

    # LEGACY

    # TODO: move to src.amatiasq.com
    location /deno {
        types {
        }
        default_type "text/plain; charset=utf-8";
        alias /repos/deno;
    }

    location = /glib {
        return 301 https://repos.amatiasq.com/glib/test/index.html;
    }

    location /important {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }

    location /slides/requirejs {
        alias /repos/requirejs-speech-amatiasq/public/;
    }

    location = /jordi {
        default_type image/jpeg;
        alias /www/regalo-jordi/imagen.jpeg;
        auth_basic "HOLA ZAPATO";
        auth_basic_user_file /www/regalo-jordi/.htaccess;
    }
}
